- id: doi:10.26508/lsa.202201650
  type: paper
  description: ** Accepted into publication in Nanoscale: ** As a service to the Expansion Microscopy community, we have characterised and catalogued 14 different reactive ester versions of aromatic fluorophores that can be used as counterstains in conjunction with Expansion Microscopy. One of the crucial observations of this work was a set of trends in which dye ester species highlighted specific sub-cellular compartments of commonly-used human carcinoma cell lines depending on ** the overall charge, time of application and ester combinations **. We reveal the fascinating variations observed with different multi-labelling experiments and highlight the need for pre-validating inter-marker interactions for any researchers looking to exploit fluorescent esters for bio-imaging.
  date: 2023-10-10
  image: images/GraphicalAbstract_Esters.jpg
  buttons:
    - type: source
      text: Manuscript Source
      link: https://www.biorxiv.org/content/10.1101/2023.02.21.529394v2
    - type: blog
      link: https://tmdsheard.github.io/blogpost9_Biophysics.html
  tags:
    - open science
    - expansion microscopy

- id: doi:10.1098/rsob.230045
  image: https://royalsocietypublishing.org/cms/asset/2a86fe9a-4462-4803-ac2b-01183f0ee894/rsob230045f01.gif

- id: doi:10.26508/lsa.202302405
  image: https://www.life-science-alliance.org/content/lsa/6/4/e202201650/F4.medium.gif
