- id: doi:10.1101/2023.02.21.529394
  image: images/GraphicalAbstract_Esters.jpg
  publisher: Nanoscale
  
- id: id: doi:10.1098/rsob.230045
  image: https://royalsocietypublishing.org/cms/asset/2a86fe9a-4462-4803-ac2b-01183f0ee894/rsob230045f01.gif
  publisher: Open Biology

- id: doi:10.1098/rstb.2021.0316
  image: https://pubs.acs.org/cms/10.1021/acsnano.8b08742/asset/images/medium/nn-2018-08742h_0001.gif
  publisher: ACS Nano
