- id: doi:10.1101/2023.02.21.529394
  image: images/GraphicalAbstract_Esters.jpg
  publisher: Nanoscale
  
- id: id: doi:10.1098/rsob.230045
  publisher: Open Biology

- id: doi:10.1098/rstb.2021.0316
  publisher: ACS Nano
